fix(api): Resource::list return empty list if the regex is not valid (#8437)
* fix(api): Resource::list return empty list if the regex is not valid

Resolve MON-5034

* fix(api): apply the PR feedback sugggestion

Resolve MON-5034

* fix(style): add the method filterByContact to the interface ResourceServiceInterface

ERROR: Call to an undefined method Centreon\Domain\Monitoring\Interfaces\ResourceServiceInterface::filterByContact()

Resolve MON-5034

* fix(api): add specific exception for invalid regex

Resolve MON-5034

* fix(api): add missing method in the interface ResourceRepositoryInterface

Resolve MON-5034

* fix(style): improve code style

Resolve MON-5034

* fix(style): improve reported code style issues

Resolve MON-5034

* fix(style): fix typo in namespace

Resolve MON-5034

* Checking the regex in the search request

* Replace the regex exception

* Surrounds the pattern with the regex delimiter

* fix(style): revert code style improvment

Resolve MON-5034

* Modification of the exception catch

* Delete useless imports into the resource repository

* Update src/Centreon/Domain/Monitoring/ResourceService.php

Co-Authored-By: Laurent Calvet <lcalvet@centreon.com>

* Raises an exception if the regex is badly formed in a production context

* Update src/Centreon/Infrastructure/RequestParameters/SqlRequestParametersTranslator.php

Co-authored-by: Laurent Calvet <laurent@callapa.com>
Co-authored-by: Laurent Calvet <lcalvet@centreon.com>